#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

progname=${0##*/}

usage() {
    echo "Usage:"
    echo "    $progname bename"
    echo "    $progname [-r release] bename"
    echo "    $progname -s [-m] bename"
    echo "    $progname -S bename"
    exit
}

exerr() {
    echo "$*" >&2
    exit 1
}

[ $(uname -r | cut -d '.' -f1) -lt 8 ] && exerr "ERROR: FreeBSD 8.0 or later required."

/usr/bin/which -s beadm
[ "$?" -ne "0" ] && exerr "ERROR: beadm is not installed."

[ $(id -u) -ne "0" ] && exerr "ERROR: Root privileges required."

while getopts :smSr: opt; do
    case $opt in
        s)   USESRC=1; INBE=1;;
        m)   PREMERGE=1;;
        S)   USESRC=1;;
        r)   RELEASE=$OPTARG;;
        '?') usage;;
    esac
done

shift $((OPTIND - 1))

BENAME=$1
[ -z $BENAME ] && usage
[ "$USESRC" -a "$RELEASE" ] && usage
[ "$USESRC" -a "$PREMERGE" ] && [ -z $INBE ] && usage

OLDIFS=$IFS
IFS=$'\n'
for line in $(beadm list -H); do
    BE=$(echo $line | cut -f1)
    ACTIVE=$(echo $line | cut -f2)
    if [ "x$BE" == "x$BENAME" ]; then
        echo $ACTIVE | grep -q N && exerr "ERROR: \"$BENAME\" is the active boot environment."
        BEFOUND=1
        break
    fi
done
IFS=$OLDIFS

[ -z $BEFOUND ] && exerr "ERROR: The boot environment \"$BENAME\" does not exist."

MNTOUT=$(beadm mount $BENAME)
[ "$?" -ne "0" ] && exerr "ERROR: Could not mount boot environment."
MNTPT=$(echo "$MNTOUT" | cut -d"'" -f2)

if [ $USESRC ]; then
    if [ $INBE ]; then
        MKOPTS="make -s buildworld && make -s buildkernel &&"
    else
        mount -t nullfs -o ro /usr/src ${MNTPT}/usr/src
        mount -t nullfs -o ro /usr/obj ${MNTPT}/usr/obj
    fi
    echo "#!/bin/sh
mount -t devfs devfs /dev
cd /usr/src
$MKOPTS make -s installkernel && make -s installworld && /usr/sbin/mergemaster -U" > ${MNTPT}/tmp/beupdate-src.sh
    chmod +x ${MNTPT}/tmp/beupdate-src.sh
    [ $PREMERGE ] && chroot ${MNTPT} /usr/sbin/mergemaster -p
    chroot ${MNTPT} /tmp/beupdate-src.sh
    rm ${MNTPT}/tmp/beupdate-src.sh
    umount ${MNTPT}/dev
    if [ -z $INBE ]; then
        umount ${MNTPT}/usr/obj
        umount ${MNTPT}/usr/src
    fi
    echo "If there were no errors, please activate \"$BENAME\" and reboot."
else
    chroot ${MNTPT} mount -t devfs devfs /dev
    if [ $RELEASE ]; then
        chroot ${MNTPT} /usr/sbin/freebsd-update upgrade -r $RELEASE
    else
        chroot ${MNTPT} /usr/sbin/freebsd-update fetch
    fi
    chroot ${MNTPT} /usr/sbin/freebsd-update install > /dev/null
    umount ${MNTPT}/dev
    echo "If there were no errors, please activate \"$BENAME\" and reboot."
    if [ $RELEASE ]; then
        echo
        echo "After rebooting, run freebsd-update again to install the new userland."
        echo "After that, reboot again."
    fi
fi

beadm umount $BENAME >/dev/null
exit

